config/routes.rb
Wearukraine::Application.routes.draw do
  devise_for :admins
  get "about/index"
  root to: 'photos#index'
  resources :photos, only: [:create, :index, :show]

  namespace :admin do
    root to: 'photos#index'
    resources :photos, only: [:destroy]
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PhotoUploader

  scope :blue, ->{ where(color: 'blue') }
  scope :yellow, ->{ where(color: 'yellow') }

  validates :color, inclusion: {in: %w[blue yellow]}, presence: true
  validates :file, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < AdminController
  def index
    @photos = Photo.all
  end

  def destroy
    Photo.destroy(params[:id])
    redirect_to :admin_root, notice: 'Photo deleted'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :html, :js

  def index
    @blue_photos      = Photo.blue
    @yellow_photos    = Photo.yellow
    @new_blue_photo   = Photo.new
    @new_yellow_photo = Photo.new
  end

  def show
    @blue_photos      = Photo.blue
    @yellow_photos    = Photo.yellow
    @new_blue_photo   = Photo.new
    @new_yellow_photo = Photo.new

    @photo = Photo.find(params[:id])
    render :index
  end

  def create
    @photo = Photo.create!(params.require(:photo).permit(:file, :color))

    respond_to do |format|
      format.html { redirect_to :root }
      format.js
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def image_url(file)
  request.protocol + request.host_with_port + path_to_image(file)
end

end

app/views/about/index.html.erb
<div class="section section-about ">
	<h2>Wear Ukraine</h2>
	<h4>Support Ukraine on the way to Europe</h4>
	<p>What to do:</p>
	<ol>
		<li>Put something on a yellow or blue</li>
		<li>Take a photo</li>
		<li>Upload your photo to your colour (yellow/blue) section</li>
	</ul>
</div>

app/views/admin/photos/index.html.erb
<ul>
  <%= content_tag_for :li, @photos do |photo| %>
  <%= image_tag photo.file.thumb.url %>
  <%= link_to 'Delete', [:admin, photo], method: :delete, confirm: 'Press OK' %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <title>WearUkraine</title>
  <%= favicon_link_tag %>
  <%= tag :meta, property: "og:title", content: "WearUkraine" %>
  <%= tag :meta, property: "og:description", content: "Підтримай Україну на шляху до Європи (Support Ukraine on the way to Europe). Вдягнись у жовтий або синій одяг та сфотографуйся (Put on something blue or yellow and take a photo)!" %>
  <%= tag :meta, property: "og:image", content: @photo ? URI.join(root_url, @photo.file.url) : image_url("wu_sharing.png") %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body style="">

<header class="main-header" role="navigation">
	<nav class="clearfix pull-left">
		<a class="logotype flag-text pull-left" href="/"><span class="yellow">WEAR</span><span class="blue">UKRAINE</span></a>
    <ul class="menu pull-left">
  		<li><a class="flag-text" href="http://www.maidanhelp.org/" target="_blank"><span class="blue">UKRAIN</span><span class="yellow">EUROPE</span></a></li>
  		<li><a data-toggle="modal" data-target="#about">ABOUT</a></li>
  	</ul>
	</nav>

	<div class="pull-left social">
      <div class="fb-like" data-href="http://wearukraine.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false" style="margin-right: 10px"></div>
      <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
    </div>
</header>


<div class="main-content">
  <%= yield %>
</div>

<!--<div class="share-area text-center">
  <div class="row">
    <div class="fb-like" data-href="http://wearukraine.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
    <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
  </div>
</div>  -->

<div class="modal fade" id="about" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog about-modal">
    <div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			</div>
      <div class="modal-body">
				 <h1>Wear Ukraine</h1>
					<h4>Support Ukraine on the way to Europe</h4>

					<p>What to do:</p>
					<ol class="flag-text">
						<li>Put on something <span class="yellow"><b>yellow</b></span> or <span class="blue"><b>blue</b></span></li>
						<li>Take a photo</li>
						<li>Upload your photo to your color (<span class="yellow"><b>yellow</b></span>/<span class="blue"><b>blue</b></span>) section</li>
					</ol>
          <br><br>
					<h4>Підтримай Україну на шляху до Європи</h4>
					<p>Що робити:</p>
					<ol class="flag-text">
						<li>Вдягнись у <span class="yellow"><b>жовтий</b></span> або <span class="blue"><b>синій</b></span> одяг</li>
						<li>Сфотографуйся</li>
						<li>Обери секцію відповідного кольору і завантаж фотографію</li>
					</ol>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="facePreview" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog about-modal">
    <div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			</div>
      <div class="modal-body">
				 <!--<h1>Share photo with your friends</h1> -->

					<img width="100%" />

					<ul class="social-links">

					</ul>

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--[if lt IE 10]>

    <script>
      alert("Web browser you use is out of-of-date or not supported. To see the content on this page correctly you have to update your browser or install a new one. Please update your browser (http://browsehappy.com/) or get a new one instead.");
    </script>
<![endif]-->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter23307619 = new Ya.Metrika({id:23307619,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/23307619" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46577956-1', 'wearukraine.com');
  ga('send', 'pageview');

</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=701720316512888";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</body>
</html>

app/views/photos/_flag_stripe.html.erb
<div class="flag-part flag-part--<%= color %>">
  <aside class="flag-face-form flag-face-form--<%= color %>">
    <a class="face-add-button"></a>
    <div class="face-add-droparea">Drag your photo in <%= color %> here</div>
    <img class="face-preview hidden" src="">
    <a class="face-upload-button">Post</a>
    <%= form_for new_photo, namespace: color, html:{multipart: true, class: "form-inline"} do |form| %>
      <%= form.file_field :file, class: 'file-input' %>
      <%= form.hidden_field :color, class: 'color-input', value: color %>
    <% end %>
  </aside>
  <ul id="<%= color %>_photos" class="flag-faces clearfix"><%= render photos, active_photo: active_photo %></ul>
</div>

app/views/photos/_photo.html.erb
<li class="flag-face" <%if active_photo == photo %>data-active<% end %> >
  <img src="<%= photo.file.thumb.url %>" alt="" data-orig-src="<%= photo.file.preview.url %>" data-share-url="<%= photo_url photo %>"/>
</li>

app/views/photos/create.js.erb
$("#<%= @photo.color %>_photos").append('<%= j(render @photo) %>');

Tools.showFace($("#<%= @photo.color %>_photos").find("li:last-child"));
Tools.drawFaces();

app/views/photos/index.html.erb
<div id="flag" class="flag">
  <%= render 'flag_stripe', color: 'blue', new_photo: @new_blue_photo, photos: @blue_photos, active_photo: @photo %>
  <%= render 'flag_stripe', color: 'yellow', new_photo: @new_yellow_photo, photos: @yellow_photos, active_photo: @photo %>
</div>